-- ============================================
-- SEED — fiches de leçon
-- 30 fiches, une par leçon, A1 -> C2.
--
-- À exécuter APRÈS migration-lesson-notes.sql (sans elle, la table n'existe
-- pas et le script échoue sans rien modifier).
-- Rejouable : `on conflict` met la fiche à jour au lieu de la dupliquer.
-- Aucune suppression, donc aucun risque pour le reste du contenu.
--
-- LE MANQUE QUE ÇA COMBLE
-- Jusqu'ici la règle n'existait que dans le champ `explanation` d'un
-- exercice — donc APRÈS s'être trompé. C'est tenable pour du vocabulaire :
-- on ne devine pas un mot, on l'apprend en le rencontrant. Ça ne l'est pas
-- pour une structure. Personne ne devine le present perfect, et se tromper
-- cinq fois avant de lire la règle n'apprend pas la règle : ça apprend qu'on
-- n'y arrive pas.
--
-- CE QUE CHAQUE FICHE CONTIENT, ET RIEN DE PLUS
--   title     la règle annoncée, pas le titre de la leçon répété
--   rule      deux à quatre phrases. Le format long est volontairement
--             impossible : une fiche qu'on ne lit pas ne sert à rien
--   examples  trois phrases, anglais ET français côte à côte. C'est la
--             comparaison qui enseigne, pas la phrase anglaise seule
--   pitfall   la faute que le francophone VA commettre. C'est souvent la
--             partie la plus utile de la fiche
--
-- POURQUOI LE FRANÇAIS À CÔTÉ DE CHAQUE EXEMPLE
-- Une fiche n'est pas un exercice : il n'y a rien à deviner ici. Cacher la
-- traduction transformerait la lecture en devinette, alors que le but est
-- justement de comprendre AVANT d'être mis à l'épreuve.
--
-- CE QUE LA FICHE N'EST PAS
-- Une activité notée. La consulter ne donne aucun XP, n'avance aucune
-- progression, n'entre dans aucune file de révision. Lire une règle n'est
-- pas la savoir, et faire croire l'inverse gonflerait la progression avec du
-- travail qui n'a pas eu lieu.
-- ============================================

insert into lesson_notes (lesson_id, title, rule, examples, pitfall) values
-- A1.1 Se présenter
(1, 'Dire son nom et son âge', 'Pour se présenter, l''anglais emploie « my name is » ou la forme courte « I''m ». Pour l''âge, il emploie le verbe ÊTRE là où le français emploie AVOIR : on ne dit pas « j''ai vingt ans » mais « je SUIS vingt ». Le mot « years old » se rajoute, ou se laisse tomber entre gens qui se comprennent.', '[{"en": "My name is Sarah.", "fr": "Je m''appelle Sarah."}, {"en": "I am twenty years old.", "fr": "J''ai vingt ans."}, {"en": "Where do you come from?", "fr": "D''où viens-tu ?"}]', '« I have twenty years » est la faute la plus reconnaissable du francophone. L''âge se dit avec « be », toujours.'),
-- A1.2 La famille
(2, 'Dire à qui appartient quoi', 'Le possesseur passe DEVANT en anglais, avec un ''s : « le mari de ma sœur » devient « my sister''s husband ». Les adjectifs possessifs (my, your, his, her) ne changent jamais de forme, quel que soit le nom qui suit.', '[{"en": "This is my sister''s husband.", "fr": "C''est le mari de ma sœur."}, {"en": "Her parents live in Lyon.", "fr": "Ses parents habitent à Lyon."}, {"en": "I do not have any brothers.", "fr": "Je n''ai pas de frères."}]', '« His » ou « her » s''accorde avec le POSSESSEUR, pas avec l''objet possédé. « Sa voiture » se dit « his car » si c''est celle d''un homme, « her car » si c''est celle d''une femme — le français ne fait pas cette différence.'),
-- A1.3 Les nombres et l'heure
(3, 'Dire l''heure', 'L''anglais annonce les MINUTES avant l''heure. On dit « a quarter past eight » (huit heures et quart) et « ten to nine » (neuf heures moins dix) : « past » pour après, « to » pour avant. La demie se dit « half past ».', '[{"en": "It is a quarter past eight.", "fr": "Il est huit heures et quart."}, {"en": "It is half past six.", "fr": "Il est six heures et demie."}, {"en": "The shop opens at nine every day.", "fr": "Le magasin ouvre à neuf heures tous les jours."}]', 'Le « et » de « huit heures et quart » n''existe pas en anglais. Et attention : « half past six » veut dire six heures trente, pas cinq heures trente.'),
-- A1.4 Nourriture et boissons
(4, 'Some, any, et « il y a »', '« Il y a » se dit « there is » au singulier, « there are » au pluriel — jamais « it is ». Devant une quantité imprécise, l''anglais met « some » à l''affirmative et « any » à la question ou à la négative.', '[{"en": "There is some milk in the fridge.", "fr": "Il y a du lait dans le frigo."}, {"en": "Is there any bread?", "fr": "Est-ce qu''il y a du pain ?"}, {"en": "I always drink tea in the morning.", "fr": "Je bois toujours du thé le matin."}]', 'Les mots qu''on ne peut pas compter (milk, bread, water, money) restent au singulier et ne prennent jamais « a » : « a bread » n''existe pas, on dit « some bread ».'),
-- A1.5 Verbes essentiels (be, have, do)
(5, 'Les trois verbes qui portent tout', '« Be » se nie et s''interroge tout seul : « we are not », « are you? ». Tous les autres verbes réclament l''auxiliaire « do/does » pour la question et la négation, et le verbe revient alors à sa forme de base — le -s est porté par l''auxiliaire.', '[{"en": "We are not late.", "fr": "Nous ne sommes pas en retard."}, {"en": "Does she have a car?", "fr": "Est-ce qu''elle a une voiture ?"}, {"en": "I do not understand.", "fr": "Je ne comprends pas."}]', '« Does she has » double la marque du -s : une fois dans « does », une fois dans « has ». Une seule suffit, et c''est l''auxiliaire qui la garde.'),
-- A2.1 Le passé simple
(6, 'Raconter ce qui est fini', 'Le passé se marque par -ed sur les verbes réguliers (worked, played), par une forme à apprendre sur les irréguliers (go → went, see → saw). À la négation et à la question, « did » prend la marque du passé et le verbe redevient nu.', '[{"en": "Yesterday I went to London.", "fr": "Hier, je suis allé à Londres."}, {"en": "She did not finish her work.", "fr": "Elle n''a pas fini son travail."}, {"en": "Did you call him?", "fr": "Est-ce que tu l''as appelé ?"}]', '« Did not finished » met le passé deux fois. Dès que « did » est là, le verbe qui suit perd sa marque de temps.'),
-- A2.2 Voyages et directions
(7, 'Demander et indiquer son chemin', 'L''impératif anglais n''a pas de sujet : « turn left », « go straight on ». Pour demander un chemin, on emploie « get to » plutôt que « go to » : « how can I GET TO the station? ». Les directions se passent de préposition — « turn left », pas « turn to the left ».', '[{"en": "How can I get to the station?", "fr": "Comment puis-je aller à la gare ?"}, {"en": "Turn left at the second traffic light.", "fr": "Tournez à gauche au deuxième feu."}, {"en": "It is on your right.", "fr": "C''est sur votre droite."}]', '« At », « in », « on » ne se devinent pas : on est AT the station, IN the town, ON the bus. Ces trois-là s''apprennent par l''usage, pas par la règle.'),
-- A2.3 Achats et argent
(8, 'Combien, et comment payer', '« How much » interroge sur une quantité qu''on ne compte pas (de l''argent, du temps), « how many » sur ce qui se compte (des articles). Pour demander poliment, « I would like » — suivi de « to » devant un verbe.', '[{"en": "How much does this shirt cost?", "fr": "Combien coûte cette chemise ?"}, {"en": "How many bags do you need?", "fr": "Combien de sacs vous faut-il ?"}, {"en": "I would like to pay by card.", "fr": "Je voudrais payer par carte."}]', '« I want » n''est pas impoli en anglais, mais il est brut. Dans un magasin, un restaurant ou un e-mail, « I would like » est ce qu''on attend.'),
-- A2.4 Décrire son quotidien
(9, 'Le présent des habitudes', 'Une habitude se dit au présent simple, avec un -s à la troisième personne (he works, she gets up). L''adverbe de fréquence (always, often, usually, never) se place AVANT le verbe — l''inverse du français.', '[{"en": "I get up at seven every morning.", "fr": "Je me lève à sept heures tous les matins."}, {"en": "He never works on Sundays.", "fr": "Il ne travaille jamais le dimanche."}, {"en": "We usually eat at home.", "fr": "Nous mangeons d''habitude à la maison."}]', 'Les verbes réfléchis français ne le sont pas en anglais : « se lever » est « get up », « se laver » est « wash ». Pas de « myself » à rajouter.'),
-- A2.5 Le futur (will / going to)
(10, 'Deux façons de parler du futur', '« Will » annonce une décision prise sur le moment, une prédiction ou une promesse. « Be going to » annonce un projet déjà décidé, ou ce qui va visiblement arriver. Les deux sont suivis du verbe à la base.', '[{"en": "We are going to move next year.", "fr": "Nous allons déménager l''année prochaine."}, {"en": "I think it will rain tomorrow.", "fr": "Je pense qu''il pleuvra demain."}, {"en": "I will help you.", "fr": "Je vais t''aider."}]', 'Après « if », « when » ou « before », l''anglais reste au PRÉSENT même quand le sens est futur : « if it rains », jamais « if it will rain ».'),
-- B1.1 Exprimer une opinion
(11, 'Donner son avis, et le placer au bon endroit', 'On dit « IN my opinion » (et non « at »), « I think that… » — où « that » se laisse tomber à l''oral. Le point délicat est la place des adverbes d''intensité : « very much » se met en FIN de phrase, jamais entre le verbe et son objet.', '[{"en": "In my opinion this film is too long.", "fr": "À mon avis, ce film est trop long."}, {"en": "I like this book very much.", "fr": "J''aime beaucoup ce livre."}, {"en": "I do not really agree.", "fr": "Je ne suis pas vraiment d''accord."}]', '« I like very much this book » se repère immédiatement comme une phrase de francophone. Et « agree » est un VERBE : « I agree », jamais « I am agree ».'),
-- B1.2 Le monde du travail
(12, 'Depuis combien de temps, et pour qui', 'Une activité commencée dans le passé et toujours vraie se dit au present perfect (« has worked »), pas au présent. « For » introduit une durée (for five years), « since » un point de départ (since 2020).', '[{"en": "She has worked for this company for five years.", "fr": "Elle travaille dans cette entreprise depuis cinq ans."}, {"en": "I have been here since March.", "fr": "Je suis ici depuis mars."}, {"en": "Can you send me the report?", "fr": "Pouvez-vous m''envoyer le rapport ?"}]', '« She works here since five years » est faux deux fois : le temps (il faut le present perfect) et la préposition (« for » pour une durée).'),
-- B1.3 Present perfect
(13, 'Le passé qui touche encore au présent', 'Le present perfect (have/has + participe) sert quand le moment n''est pas précisé, ou quand le passé compte encore aujourd''hui. Dès qu''une date ou un moment fini apparaît (yesterday, in 1990, last week), on repasse au passé simple.', '[{"en": "I have never visited Scotland.", "fr": "Je n''ai jamais visité l''Écosse."}, {"en": "Have you finished yet?", "fr": "As-tu déjà fini ?"}, {"en": "I saw him yesterday.", "fr": "Je l''ai vu hier."}]', '« Never » et « already » se glissent ENTRE l''auxiliaire et le participe : « have NEVER visited ». Le français les met après, d''où « I have visited never ».'),
-- B1.4 Santé et bien-être
(14, 'Dire comment on se sent, et conseiller', 'Sur la santé on dit « well », pas « good » : « I feel well ». Le conseil passe par « should », et comme tous les modaux (can, must, will, may) il est suivi du verbe NU, sans « to ».', '[{"en": "I do not feel very well today.", "fr": "Je ne me sens pas très bien aujourd''hui."}, {"en": "You should see a doctor.", "fr": "Tu devrais voir un médecin."}, {"en": "You must not smoke here.", "fr": "Vous ne devez pas fumer ici."}]', '« You should to see » est une faute quasi systématique chez les francophones, parce que le français dit « tu devrais VOIR » avec un infinitif. En anglais, après un modal, pas de « to ».'),
-- B1.5 Comparatifs et superlatifs
(15, 'Comparer deux choses, puis toutes', 'Un adjectif court prend -er au comparatif et the -est au superlatif (fast → faster → the fastest). Un adjectif long prend « more » et « the most » (expensive → more expensive). La comparaison s''introduit par « than ».', '[{"en": "This train is faster than the other one.", "fr": "Ce train est plus rapide que l''autre."}, {"en": "It is the best restaurant in town.", "fr": "C''est le meilleur restaurant de la ville."}, {"en": "This is more expensive than I thought.", "fr": "C''est plus cher que je ne le pensais."}]', 'Après un superlatif, le lieu s''introduit par « in », pas « of » : « the best restaurant IN town ». Et « good » est irrégulier : good → better → the best.'),
-- B2.1 Débattre et argumenter
(16, 'Enchaîner ses arguments', 'L''anglais dispose de charnières précises : « however » (cependant) ouvre une phrase, « although » (bien que) ouvre une subordonnée, « on the one hand… on the other hand » oppose deux faces d''un même sujet. Le désaccord se renforce en fin de phrase avec « at all ».', '[{"en": "I do not agree with this idea at all.", "fr": "Je ne suis pas du tout d''accord avec cette idée."}, {"en": "On the one hand it would be very expensive.", "fr": "D''une part, cela coûterait très cher."}, {"en": "However, the results are encouraging.", "fr": "Cependant, les résultats sont encourageants."}]', '« Although » et « but » ne se cumulent pas. « Although it is expensive, but it works » contient deux fois la même opposition : il faut en choisir une.'),
-- B2.2 Conditionnels (1st, 2nd)
(17, 'Si… alors', 'Premier conditionnel, pour ce qui peut arriver : « if » + présent, puis « will ». Deuxième conditionnel, pour l''hypothèse ou l''irréel : « if » + passé simple, puis « would ». Dans les deux cas, le « will » ou le « would » ne franchit JAMAIS le « if ».', '[{"en": "We will stay at home if it rains.", "fr": "Nous resterons à la maison s''il pleut."}, {"en": "If I had more time I would learn the piano.", "fr": "Si j''avais plus de temps, j''apprendrais le piano."}, {"en": "If I were you I would wait.", "fr": "Si j''étais toi, j''attendrais."}]', '« If I would have more time » met le conditionnel des deux côtés. Un seul côté le porte — celui qui n''a pas le « if ».'),
-- B2.3 Environnement et société
(18, 'Parler de tendances et de quantités', 'Une tendance se dit « more and more » ou « fewer and fewer ». « People » est déjà pluriel : pas de -s, et le verbe suit sans -s. Après « before » et « until », l''anglais reste au présent.', '[{"en": "More and more people use public transport.", "fr": "De plus en plus de gens utilisent les transports en commun."}, {"en": "We must act before it is too late.", "fr": "Nous devons agir avant qu''il ne soit trop tard."}, {"en": "Fewer people drive to work now.", "fr": "Moins de gens vont travailler en voiture aujourd''hui."}]', '« Fewer » compte (fewer cars), « less » ne compte pas (less pollution). L''anglais courant les confond ; à l''écrit, la distinction se voit.'),
-- B2.4 Voix passive
(19, 'Quand l''auteur de l''action passe au second plan', 'Le passif se construit avec « be » au temps voulu + le participe passé : « is built », « was built », « has been built ». L''auteur de l''action, s''il est nommé, s''introduit par « BY » — jamais « from ».', '[{"en": "This bridge was built in 1890.", "fr": "Ce pont a été construit en 1890."}, {"en": "The meeting was cancelled by the manager.", "fr": "La réunion a été annulée par le directeur."}, {"en": "English is spoken here.", "fr": "On parle anglais ici."}]', 'Le « on » impersonnel français n''a pas d''équivalent direct : « on parle anglais » devient un passif (« English is spoken ») ou « they speak English ». « One speaks » existe mais sonne très formel.'),
-- B2.5 Anglais professionnel
(20, 'Écrire un e-mail qui passe', 'L''e-mail professionnel anglais suit des formules fixes qu''il vaut mieux apprendre telles quelles : « I am writing to… » pour annoncer l''objet, « please do not hesitate to… » pour clore, « Yours sincerely » quand on connaît le nom du destinataire.', '[{"en": "I am writing to apply for this position.", "fr": "Je vous écris pour postuler à ce poste."}, {"en": "Please do not hesitate to contact me.", "fr": "N''hésitez pas à me contacter."}, {"en": "I look forward to hearing from you.", "fr": "Dans l''attente de votre réponse."}]', 'Le but se dit « to » + verbe, jamais « for » + verbe : « I am writing TO apply ». En revanche on « applies FOR a position » — la préposition change de rôle.'),
-- C1.1 Nuances et registres de langue
(21, 'L''inversion après un adverbe négatif', 'Quand un adverbe négatif ou restrictif ouvre la phrase (never, rarely, hardly, seldom, little, only), l''anglais INVERSE l''auxiliaire et le sujet, exactement comme dans une question. C''est une structure sans aucun équivalent français, et la marque d''un registre soutenu.', '[{"en": "Never had I seen such a thing.", "fr": "Je n''avais jamais vu une telle chose."}, {"en": "Rarely does he speak in public.", "fr": "Il parle rarement en public."}, {"en": "It is not so much a question of money as of time.", "fr": "Ce n''est pas tant une question d''argent que de temps."}]', 'L''inversion n''est pas plus CORRECTE que l''ordre normal : « I had never seen such a thing » est juste aussi. Elle est plus soutenue, et déplace l''insistance sur le « jamais ».'),
-- C1.2 Conditionnels avancés (3rd, mixed)
(22, 'Le regret et le reproche', 'Troisième conditionnel, pour ce qui ne s''est pas produit : « if » + plus-que-parfait, puis « would have » + participe. C''est le temps du regret. « Should have » + participe exprime le reproche.', '[{"en": "If I had known I would not have come.", "fr": "Si j''avais su, je ne serais pas venu."}, {"en": "She should have told us earlier.", "fr": "Elle aurait dû nous le dire plus tôt."}, {"en": "You could have asked me.", "fr": "Tu aurais pu me demander."}]', '« Must have » n''est pas le reproche mais la DÉDUCTION : « she must have told us » veut dire « elle a dû nous le dire » au sens de « c''est sûrement ce qui s''est passé ».'),
-- C1.3 Actualités et médias
(23, 'Rapporter sans endosser', 'La presse anglaise marque la distance autrement que le français. Notre conditionnel journalistique (« le rapport aurait été divulgué ») se rend par « is said to have been », « is reported to », « allegedly » — pas par « would ».', '[{"en": "The report is said to have been leaked last week.", "fr": "Le rapport aurait été divulgué la semaine dernière."}, {"en": "He is reported to be in Berlin.", "fr": "Il serait à Berlin."}, {"en": "Rarely has an election aroused so much interest.", "fr": "Rarement une élection a suscité autant d''intérêt."}]', 'Traduire « aurait été divulgué » par « would have been leaked » change complètement le sens : on passe d''une information non confirmée à une hypothèse irréelle.'),
-- C1.4 Expressions idiomatiques
(24, 'Une image ne se traduit pas', 'Les expressions idiomatiques ont un ordre de mots figé et une image propre à chaque langue. Traduire mot à mot ne produit rien de compréhensible : il faut apprendre l''expression entière, comme un seul mot.', '[{"en": "He let the cat out of the bag.", "fr": "Il a vendu la mèche."}, {"en": "That does not ring a bell at all.", "fr": "Ça ne me dit rien du tout."}, {"en": "It is not my cup of tea.", "fr": "Ce n''est pas mon truc."}]', 'Une expression ne se modifie pas : « let the cats out of the bags » ne veut plus rien dire. Le pluriel, l''article, la préposition font partie de l''expression.'),
-- C1.5 Rédaction argumentative
(25, 'Les charnières de l''écrit', 'À l''écrit argumenté, l''anglais emploie des tournures impersonnelles (« it should be pointed out that… ») et des couples fixes (« not only… but also »). « Not only » en tête de phrase entraîne l''inversion sur la PREMIÈRE moitié seulement.', '[{"en": "Not only is it expensive but it is also ineffective.", "fr": "Non seulement c''est coûteux, mais c''est aussi inefficace."}, {"en": "It should be pointed out that the data remain incomplete.", "fr": "Il convient de souligner que les données restent incomplètes."}, {"en": "Furthermore, the method has never been tested.", "fr": "De plus, la méthode n''a jamais été testée."}]', 'L''asymétrie de « not only… but also » surprend : la première moitié s''inverse, la seconde reste normale. Et « data » se traite comme un pluriel à l''écrit soigné : « the data REMAIN ».'),
-- C2.1 Registres académiques et littéraires
(26, 'Concéder avec élégance', 'Le registre académique dispose de concessives inversées : l''adjectif ouvre la phrase, suivi de « as… may be » (« convincing as the argument may be »). Elles disent la même chose que « although », dans un registre plus haut.', '[{"en": "Convincing as the argument may be it remains theoretical.", "fr": "Aussi convaincant que soit l''argument, il reste théorique."}, {"en": "Only then did the true scale become apparent.", "fr": "Ce n''est qu''alors que la véritable ampleur est apparue."}, {"en": "Such was the outcry that the plan was dropped.", "fr": "Le tollé fut tel que le projet fut abandonné."}]', 'Ces tournures ne s''emploient pas à l''oral courant : dans une conversation, elles sonnent affectées. Le registre est un outil, pas une amélioration.'),
-- C2.2 Subtilités phonétiques et accents
(27, 'L''accent qui change le mot', 'En anglais, la place de l''accent tonique peut changer la nature d''un mot : REcord (un enregistrement, nom) et reCORD (enregistrer, verbe) s''écrivent pareil. Le français accentue régulièrement la fin des mots, ce qui efface cette distinction.', '[{"en": "I want to record this record.", "fr": "Je veux enregistrer ce disque."}, {"en": "It was not what he said so much as the way he said it.", "fr": "Ce n''est pas tant ce qu''il a dit que la façon dont il l''a dit."}, {"en": "Hardly had she spoken when the room fell silent.", "fr": "À peine avait-elle parlé que la salle s''est tue."}]', 'La règle vaut pour beaucoup de paires nom/verbe : PREsent / preSENT, OBject / obJECT, PROduce / proDUCE. Le nom porte l''accent devant, le verbe derrière.'),
-- C2.3 Négociation et diplomatie
(28, 'Fermeté et prudence', 'La négociation anglaise repose sur des formules figées : « under no circumstances » (qui entraîne l''inversion) marque le refus absolu, « we would be prepared to » l''ouverture prudente. Le conditionnel adoucit sans engager.', '[{"en": "Under no circumstances will we accept these terms.", "fr": "En aucun cas nous n''accepterons ces conditions."}, {"en": "We would be prepared to reconsider our offer.", "fr": "Nous serions disposés à revoir notre offre."}, {"en": "That may prove difficult.", "fr": "Cela pourrait s''avérer difficile."}]', '« Prepared TO » annonce une action, « prepared FOR » annonce un nom : « prepared to reconsider » mais « prepared for the meeting ». La préposition change ce qui suit.'),
-- C2.4 Humour, ironie et sous-entendus
(29, 'La litote anglaise', 'L''humour anglais passe souvent par la litote : on dit moins pour signifier plus. « Not delighted » veut dire furieux, « not bad » veut dire très bon. Les formules « not what you would call… » et « suffice it to say… » annoncent l''ironie.', '[{"en": "He is not what you would call a patient man.", "fr": "Ce n''est pas ce qu''on appellerait un homme patient."}, {"en": "Suffice it to say he was not delighted.", "fr": "Autant dire qu''il n''était pas ravi."}, {"en": "That went about as well as expected.", "fr": "Ça s''est passé à peu près comme prévu."}]', 'La litote se rate en la prenant au premier degré : « not bad » n''est pas un reproche poli, c''est un compliment. Le ton et le contexte tranchent, pas les mots.'),
-- C2.5 Maîtrise totale : synthèse
(30, 'Tout ce qui déclenche une inversion', 'Récapitulatif : l''inversion se déclenche après un adverbe négatif ou restrictif en tête (never, rarely, hardly, only, not only), après « so » et « such » d''intensité, et dans les conditionnelles sans « if » (« had I known… »). Partout ailleurs, l''ordre reste sujet-verbe.', '[{"en": "Only by listening carefully can one grasp the nuance.", "fr": "Ce n''est qu''en écoutant attentivement qu''on saisit la nuance."}, {"en": "Had I known, I would have said nothing.", "fr": "Si j''avais su, je n''aurais rien dit."}, {"en": "Whatever happens we will keep our commitments.", "fr": "Quoi qu''il arrive, nous tiendrons nos engagements."}]', '« Whatever », « whoever », « however » n''entraînent PAS d''inversion : « whatever happens we will… ». Seuls les négatifs et restrictifs le font.')
on conflict (lesson_id) do update set
  title = excluded.title,
  rule = excluded.rule,
  examples = excluded.examples,
  pitfall = excluded.pitfall;

-- ============================================
-- VÉRIFICATION — doit renvoyer 30, puis aucune ligne.
-- ============================================
select count(*) as total_fiches from lesson_notes;

-- Leçons SANS fiche : doit être vide.
select l.id, l.level, l.title
from lessons l
left join lesson_notes n on n.lesson_id = l.id
where n.lesson_id is null
order by l.id;
